feat: add GitHub Actions setup for dependency management and testing workflows

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -2,39 +2,81 @@ name: Run Tests
 
 on:
   push:
-    branches: [main]
+    branches:
+      - main
+    paths:
+      - url-shortener-service/**
+      - url-shortener-web/**
   pull_request:
-    branches: [main]
   workflow_dispatch:
 
 jobs:
-  test-url-shortener-service:
-    runs-on: ubuntu-latest
-
+  filter:
+    runs-on: ubuntu-24.04
+    outputs:
+      services: ${{ steps.filter.outputs.changes }}
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v6.0.2
+      - uses: actions/checkout@v6.0.2
+      - name: Paths Changes Filter
+        id: filter
+        uses: dorny/paths-filter@v4
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          filters: .github/utils/file-filters.yaml
 
-    - name: Set up Python
-      uses: actions/setup-python@v5
-      with:
-        python-version: "3.14.2"
+  run-tests:
+    runs-on: ubuntu-24.04
+    if: ${{ needs.filter.outputs.services != '[]' && needs.filter.outputs.services != '' }}
+    needs: filter
+    strategy:
+      matrix:
+        service: ${{ fromJson(needs.filter.outputs.services) }}
+      fail-fast: false
+    steps:
+      - uses: actions/checkout@v6.0.2
+      - uses: ./.github/setup-dependencies
+        with:
+          install_node: ${{ matrix.service == 'url-shortener-web' }}
+          install_python: ${{ matrix.service == 'url-shortener-service' }}
+          service_path: ${{ matrix.service }}
 
-    - name: Install dependencies
-      working-directory: url-shortener-service
-      run: |
-        python -m pip install --upgrade pip
-        pip install \
-          fastapi \
-          starlette \
-          pydantic[email] \
-          python-dotenv \
-          asyncpg \
-          httpx \
-          pytest \
-          pytest-asyncio \
-          pytest-mock
+      - name: Install dependencies
+        working-directory: ${{ matrix.service }}
+        run: |
+          if [ "${{ matrix.service }}" = "url-shortener-web" ]; then
+            npm ci
+          else
+            python -m pip install --upgrade pip
+            pip install \
+              fastapi \
+              starlette \
+              pydantic[email] \
+              python-dotenv \
+              asyncpg \
+              httpx \
+              pytest \
+              pytest-asyncio \
+              pytest-mock
+          fi
 
-    - name: Run tests
-      working-directory: url-shortener-service
-      run: pytest
+      - name: Run tests
+        working-directory: ${{ matrix.service }}
+        run: |
+          if [ "${{ matrix.service }}" = "url-shortener-web" ]; then
+            npm test
+          else
+            pytest
+          fi
+
+  # Ensures a merge-blocking failure if upstream jobs fail. 
+  # We avoid skipping because GitHub’s "Required Checks" do not block merges on a skipped status.
+  run-tests-failure-alert:
+    runs-on: ubuntu-latest
+    needs: [filter, run-tests]
+    if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
+    steps:
+      - name: Conditionally Fail Required Check
+        shell: bash
+        run: |
+          echo "::error Some required job has failed!"
+          exit 1
